# å·¥ä½œæµç¨‹çš„åç§°
name: Hexo Deploy Aliyun
run-name: Hexo Deploy Aliyun ğŸš€

on:
<<<<<<< HEAD
  push:
=======
  workflow_dispatch:
  # push:
  #   branches:
  #     - blog
>>>>>>> blog

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run a script if on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "Running a script because this is the main branch."

      - name: Run a different script if on develop branch
        if: github.ref == 'refs/heads/blog'
        run: echo "Running a different script because this is the develop branch."
